"""Moxi's public package boundary."""

from .accessibility import (
    AccessibilitySnapshot,
    ROLE_BUTTON,
    ROLE_CHECKBOX,
    ROLE_CONTAINER,
    ROLE_LABEL,
    ROLE_NONE,
    ROLE_SPACER,
    ROLE_TEXT_INPUT,
    ROLE_PROGRESS_INDICATOR,
    ROLE_SLIDER,
    ROLE_SWITCH,
    ROLE_RADIO,
    ROLE_IMAGE,
    ROLE_TEXT_AREA,
    ROLE_COMBO_BOX,
    ROLE_LIST,
    ROLE_TABLE,
    ROLE_TREE,
    ROLE_MENU,
    ROLE_DIALOG,
    ROLE_TAB_GROUP,
    ROLE_CANVAS,
    ROLE_SEPARATOR,
    Semantics,
    ACTION_NONE,
    ACTION_PRESS,
    ACTION_INCREMENT,
    ACTION_DECREMENT,
    ACTION_SELECT,
    ACTION_EXPAND,
    ACTION_COLLAPSE,
)
from .geometry import Point, Rect, Size, Transform
from .backend import (
    BACKEND_GPU,
    BACKEND_HEADLESS,
    BACKEND_LINUX,
    BACKEND_MACOS_APPKIT,
    BACKEND_WINDOWS,
    BACKEND_IOS,
    BACKEND_ANDROID,
    BACKEND_WEB,
    BackendCapabilities,
    backend_capabilities,
)
from .event import (
    CLICK_KIND,
    COMPOSITION_END_KIND,
    COMPOSITION_UPDATE_KIND,
    FRAME_TICK_KIND,
    KEY_BACKSPACE,
    KEY_A,
    KEY_C,
    KEY_DELETE,
    KEY_DOWN,
    KEY_END,
    KEY_ENTER,
    KEY_ESCAPE,
    KEY_HOME,
    KEY_LEFT,
    KEY_RIGHT,
    KEY_SPACE,
    KEY_TAB,
    KEY_V,
    KEY_X,
    KEY_UP,
    POINTER_MOVE_KIND,
    POINTER_UP_KIND,
    SCROLL_KIND,
    DRAG_BEGIN_KIND,
    DRAG_UPDATE_KIND,
    DROP_KIND,
    TASK_RESULT_KIND,
    TOUCH_BEGIN_KIND,
    TOUCH_UPDATE_KIND,
    TOUCH_END_KIND,
    POINTER_CANCEL_KIND,
    ACTION_KIND,
    KEY_DOWN_KIND,
    MOD_COMMAND,
    MOD_CONTROL,
    MOD_OPTION,
    MOD_SHIFT,
    NONE_KIND,
    NO_ACTION,
    POINTER_DOWN_KIND,
    TEXT_INPUT_KIND,
    WINDOW_RESIZED_KIND,
    ClickEvent,
    CompositionEvent,
    Event,
    FrameEvent,
    KeyEvent,
    PointerEvent,
    TouchEvent,
    ResizeEvent,
    ScrollEvent,
    TaskEvent,
    DragEvent,
    ActionEvent,
    SemanticActionEvent,
    TextInputEvent,
)
from .component import Component, ComponentSlot, KeyedSubtreeDescriptor
from .clipboard import ClipboardBackend, MemoryClipboard
from .capability_types import (
    CALLER_AGENT,
    CALLER_SYSTEM,
    CALLER_UI,
    CAPABILITY_BUSY,
    CAPABILITY_DISABLED,
    CAPABILITY_EXECUTOR_REQUIRED,
    CAPABILITY_HANDLER_MISMATCH,
    CAPABILITY_HANDLER_NOT_REGISTERED,
    CAPABILITY_INVALID,
    CAPABILITY_NOT_FOUND,
    CAPABILITY_OK,
    CAPABILITY_QUEUE_FULL,
    CAPABILITY_REQUIRES_APPROVAL,
    CAPABILITY_SCHEMA_INVALID,
    CAPABILITY_UNAVAILABLE,
    CapabilityApproval,
    CapabilityDescriptor,
    CapabilityInvocation,
    CapabilityResult,
    SIDE_EFFECT_DESTRUCTIVE,
    SIDE_EFFECT_LOCAL,
    SIDE_EFFECT_NETWORK,
    SIDE_EFFECT_NONE,
)
from .capability_bus import CapabilityBus, CapabilityHandler
from .conversation import ChatMessage, ConversationContext
from .capability_walkthrough import (
    CAPABILITY_WALKTHROUGH_STEP_COUNT,
    CAPABILITY_WALKTHROUGH_TITLE_ID,
    CAPABILITY_WALKTHROUGH_STEP_ID,
    CAPABILITY_WALKTHROUGH_BODY_ID,
    CAPABILITY_WALKTHROUGH_PROGRESS_ID,
    CAPABILITY_WALKTHROUGH_PREVIOUS_ID,
    CAPABILITY_WALKTHROUGH_NEXT_ID,
    CAPABILITY_WALKTHROUGH_RESTART_ID,
    CAPABILITY_WALKTHROUGH_AGENT_RESET_ID,
    CAPABILITY_WALKTHROUGH_APPROVE_ID,
    CAPABILITY_WALKTHROUGH_STATUS_ID,
    CAPABILITY_WALKTHROUGH_BUS_ID,
    CAPABILITY_WALKTHROUGH_HINT_ID,
    CapabilityWalkthroughHandler,
    CapabilityWalkthroughState,
    capability_walkthrough_step_count,
)
from .controls_basic import (
    ButtonControl,
    CheckboxControl,
    ImageControl,
    LabelControl,
    CanvasControl,
    SeparatorControl,
    ProgressControl,
    RadioControl,
    SliderControl,
    SwitchControl,
)
from .controls_text import (
    MultilineTextControl,
    TextInputControl,
    TextInputState,
    MultilineTextState,
)
from .controls_collection import (
    ComboBoxControl,
    ListControl,
    TableControl,
    TreeControl,
    MenuControl,
    DialogControl,
    TabsControl,
)
from .controls_state import (
    SliderState,
    ToggleState,
    RadioGroupState,
)
from .control_state import (
    CanvasState,
    ComboBoxState,
    DialogState,
    ListState,
    MenuState,
    SelectionState,
    TableState,
    TabsState,
    TreeState,
)
from .collection_state import (
    COLLECTION_NONE,
    COLLECTION_SINGLE,
    COLLECTION_MULTIPLE,
    COLUMN_SORT_NONE,
    COLUMN_SORT_ASCENDING,
    COLUMN_SORT_DESCENDING,
    CollectionColumn,
    CollectionSelection,
    ReorderResult,
    TreeCollectionState,
    TreeNodeRecord,
)
from .scrollbar import (
    SCROLLBAR_VERTICAL,
    SCROLLBAR_HORIZONTAL,
    SCROLLBAR_HIT_NONE,
    SCROLLBAR_HIT_THUMB,
    SCROLLBAR_HIT_TRACK,
    SCROLLBAR_NO_COMMAND,
    SCROLLBAR_STEP_BACKWARD,
    SCROLLBAR_STEP_FORWARD,
    SCROLLBAR_PAGE_BACKWARD,
    SCROLLBAR_PAGE_FORWARD,
    SCROLLBAR_HOME,
    SCROLLBAR_END,
    ScrollbarGeometry,
    ScrollbarState,
)
from .popup import (
    POPUP_NONE,
    POPUP_COMBO,
    POPUP_MENU,
    POPUP_CONTEXT_MENU,
    POPUP_DIALOG,
    POPUP_PLACE_BELOW,
    POPUP_PLACE_ABOVE,
    POPUP_PLACE_RIGHT,
    POPUP_PLACE_LEFT,
    POPUP_NO_ACTION,
    PopupEntry,
    PopupLayerState,
    place_popup,
)
from .reorder import (
    REORDER_IDLE,
    REORDER_ARMED,
    REORDER_DRAGGING,
    REORDER_CANCELLED,
    REORDER_DROPPED,
    REORDER_NO_INDEX,
    ReorderInteraction,
)
from .interaction_showcase import (
    INTERACTION_SHOWCASE_CANVAS_ID,
    INTERACTION_SHOWCASE_SELECT_NEXT_ID,
    INTERACTION_SHOWCASE_MOVE_ID,
    INTERACTION_SHOWCASE_SCROLL_BACK_ID,
    INTERACTION_SHOWCASE_SCROLL_FORWARD_ID,
    INTERACTION_SHOWCASE_TREE_ID,
    INTERACTION_SHOWCASE_MENU_ID,
    INTERACTION_SHOWCASE_DIALOG_ID,
    INTERACTION_SHOWCASE_SORT_ID,
    INTERACTION_SHOWCASE_RESET_ID,
    InteractionShowcaseState,
)
from .app import COUNTER_INCREMENT_ACTION, CounterState
from .alignment import AlignmentState
from .app_runtime import App
from .form import FormState
from .theme_showcase import ThemeShowcaseState
from .composed import (
    COMPOSED_COUNTER_ID_OFFSET,
    COMPOSED_COUNTER_SLOT_ID,
    COMPOSED_TITLE_ID,
    ComposedState,
)
from .nested import NestedState
from .row import NEXT_BUTTON_ID, PREVIOUS_BUTTON_ID, RowState
from .wxstyle import (
    WX_ACTIONS_ID,
    WX_AGENT_RESET_BUTTON_ID,
    WX_AGENT_RESET_ACTION,
    WX_APPROVE_RESET_ID,
    WX_APPROVE_RESET_ACTION,
    WX_APPROVAL_STATUS_ID,
    WX_ADVANCED_ID,
    WX_SLIDER_ID,
    WX_SWITCH_ID,
    WX_RADIO_ID,
    WX_IMAGE_ID,
    WX_MULTILINE_ID,
    WX_COMBO_ID,
    WX_LIST_ID,
    WX_TABLE_ID,
    WX_TREE_ID,
    WX_MENU_ID,
    WX_DIALOG_ID,
    WX_TABS_ID,
    WX_CANVAS_ID,
    WX_SEPARATOR_ID,
    WX_BACKEND_ID,
    WX_BODY_ID,
    WX_CANCEL_BUTTON_ID,
    WX_CAPABILITIES_ID,
    WX_CAPABILITY_STATUS_ID,
    WX_COMPONENT_SLOT_ID,
    WX_COUNTER_ID_OFFSET,
    WX_CONTEXT_ID,
    WX_HEADER_ID,
    WX_HELP_ID,
    WX_LAYOUT_ID,
    WX_NAME_FIELD_ID,
    WX_NAME_LABEL_ID,
    WX_OK_BUTTON_ID,
    WX_PANEL_ID,
    WX_PROGRESS_ID,
    WX_RICH_TEXT_ID,
    WX_REMEMBER_ID,
    WX_RESET_BUTTON_ID,
    WX_SPACER_ID,
    WX_STATUS_ID,
    WX_SUBTITLE_ID,
    WX_SUBMIT_ACTION,
    WX_CANCEL_ACTION,
    WX_REMEMBER_ACTION,
    WX_RESET_ACTION,
    WX_TITLE_ID,
    WxStyleState,
)
from .wrapped import WRAPPED_BODY_ID, WRAPPED_TITLE_ID, WrappedTextState
from .layout import (
    ALIGN_CENTER,
    ALIGN_END,
    ALIGN_START,
    ALIGN_STRETCH,
    COLUMN_AXIS,
    JUSTIFY_CENTER,
    JUSTIFY_END,
    JUSTIFY_SPACE_BETWEEN,
    JUSTIFY_START,
    ROW_AXIS,
    ColumnLayout,
    RowLayout,
    LAYOUT_GRID,
    LAYOUT_LINEAR,
    LAYOUT_PORTAL,
    LAYOUT_SPLIT,
    LAYOUT_STACK,
)
from .layout_primitives import (
    GridCell,
    ScrollState,
    VirtualRange,
    VirtualListState,
    VirtualRecycleItem,
    VirtualRecycler,
    clamp_fraction,
    grid_cell,
    split_extent,
    variable_visible_range,
    visible_range,
)
from .measure import TextMeasurement, measure_text, measure_text_wrapped
from .text_layout import (
    TEXT_DIRECTION_LTR,
    TEXT_DIRECTION_RTL,
    TEXT_DIRECTION_AUTO,
    TEXT_LAYOUT_ESTIMATE,
    TEXT_LAYOUT_NATIVE,
    TEXT_LAYOUT_PORTABLE,
    RichText,
    TextLayoutRequest,
    TextLayoutResult,
    TextSpan,
    layout_rich_text,
    layout_text,
)
from .text_shaping import (
    SHAPER_NATIVE,
    SHAPER_PORTABLE_ESTIMATE,
    SCRIPT_ARABIC_HEBREW,
    SCRIPT_CJK,
    SCRIPT_COMMON,
    SCRIPT_CYRILLIC,
    SCRIPT_DEVANAGARI,
    SCRIPT_EMOJI,
    SCRIPT_LATIN,
    PortableTextShaper,
    ShapedGlyph,
    ShapedRun,
    ShapedText,
    TextShaper,
    fallback_font_id,
    script_id,
    shape_text,
)
from .text_boundary import (
    clamp_text_boundary,
    codepoint_at,
    is_combining_mark,
    is_emoji_modifier,
    is_extend,
    is_regional_indicator,
    is_variation_selector,
    next_text_boundary,
    previous_text_boundary,
)
from .reactivity import (
    ActionMessage,
    ActionQueue,
    MemoKey,
    StateScope,
    StateVersion,
    StringLens,
    StringMemo,
)
from .tasks import (
    TASK_CANCELLED,
    TASK_COMPLETED,
    TASK_FAILED,
    TASK_PENDING,
    TaskHandle,
    TaskRecord,
    TaskResult,
    TaskScheduler,
)
from .resources import (
    RESOURCE_DATA,
    RESOURCE_FONT,
    RESOURCE_IMAGE,
    RESOURCE_NONE,
    ImageResource,
    FontResource,
    ResourceHandle,
    ResourceResolver,
    ResourceStore,
)
from .scene import (
    SCENE_CLIP,
    SCENE_IMAGE,
    SCENE_LINE,
    SCENE_POP_CLIP,
    SCENE_POP_LAYER,
    SCENE_PUSH_LAYER,
    SCENE_RECT,
    SCENE_ROUNDED_RECT,
    SCENE_TEXT,
    SCENE_PATH,
    SCENE_LINEAR_GRADIENT,
    SCENE_TRANSFORM,
    SCENE_RESET_TRANSFORM,
    Scene,
    SceneCommand,
    SceneRenderer,
    SceneRecorder,
)
from .scene_path import (
    SCENE_PATH_CLOSE,
    SCENE_PATH_CUBIC_TO,
    SCENE_PATH_LINE_TO,
    SCENE_PATH_MOVE_TO,
    SCENE_PATH_QUAD_TO,
    ScenePath,
    ScenePathCommand,
)
from .scene_text import (
    TEXT_ALIGN_CENTER,
    TEXT_ALIGN_END,
    TEXT_ALIGN_START,
    TEXT_BASELINE_ALPHABETIC,
    TEXT_BASELINE_HANGING,
    TEXT_BASELINE_MIDDLE,
    SCENE_TEXT_DIRECTION_AUTO,
    SCENE_TEXT_DIRECTION_LTR,
    SCENE_TEXT_DIRECTION_RTL,
    SceneTextStyle,
)
from .fractal import (
    FRACTAL_CANVAS_HEIGHT,
    FRACTAL_CANVAS_ID,
    FRACTAL_CANVAS_WIDTH,
    FRACTAL_SCROLL_ID,
    FRACTAL_DEPTH_UP_ID,
    FRACTAL_GUIDES_ID,
    FRACTAL_GROUP_CLASSIC,
    FRACTAL_GROUP_EXPERIMENT,
    FRACTAL_MAX_DEPTH,
    FRACTAL_MAX_RENDERED_SEGMENTS,
    FRACTAL_PRESET_BUTTON_BASE,
    FRACTAL_PRESET_COUNT,
    FractalCanvasPainter,
    FractalGeometry,
    FractalSegment,
    FractalState,
    fractal_preset_group,
    fractal_preset_geometry,
    fractal_preset_name,
)
from .software import SoftwareSceneRenderer
from .canvas_renderer import (
    CANVAS_RENDER_OK,
    CANVAS_RENDER_UNBALANCED_CLIP,
    CANVAS_RENDER_UNBALANCED_LAYER,
    CANVAS_RENDER_INVALID_BOUNDS,
    CANVAS_RENDER_INVALID_STROKE,
    CanvasSceneRenderer,
)
from .invalidation import (
    INVALIDATE_ACCESSIBILITY,
    INVALIDATE_ALL,
    INVALIDATE_CONTENT,
    INVALIDATE_LAYOUT,
    INVALIDATE_NONE,
    INVALIDATE_STRUCTURE,
    Invalidation,
)
from .animation import (
    EASE_IN,
    EASE_IN_OUT,
    EASE_LINEAR,
    EASE_OUT,
    Animation,
    eased_progress,
)
from .paint import PANEL_KIND, SURFACE_KIND, PaintCommand, PaintCommands, Renderer, scene_from_paint
from .column_runtime import ColumnRuntime
from .legacy_runtime import CounterRuntime, Runtime
from .widget import Widget
from .style import (
    Color,
    Panel,
    Style,
    Theme,
    default_button_style,
    default_checkbox_style,
    default_label_style,
    default_panel_style,
    default_progress_style,
    default_surface_style,
    default_text_input_style,
    default_image_style,
    default_multiline_style,
    default_radio_style,
    default_slider_style,
    default_switch_style,
)
from .tokens import (
    ColorTokens,
    RadiusTokens,
    SpacingTokens,
    ThemeTokens,
    TypographyTokens,
    dark_tokens,
    light_tokens,
    zinc_tokens,
    emerald_tokens,
    theme_from_tokens,
    dark_theme,
    light_theme,
    zinc_theme,
    emerald_theme,
)
from .recipes import (
    primary_button,
    secondary_button,
    destructive_button,
    outline_button,
    ghost_button,
    badge,
    card_panel,
)
from .view import (
    BUTTON_KIND,
    CHECKBOX_KIND,
    LABEL_KIND,
    SLIDER_KIND,
    SWITCH_KIND,
    RADIO_KIND,
    IMAGE_KIND,
    MULTILINE_TEXT_KIND,
    COMBO_BOX_KIND,
    LIST_KIND,
    TABLE_KIND,
    TREE_KIND,
    MENU_KIND,
    DIALOG_KIND,
    TABS_KIND,
    CANVAS_KIND,
    SEPARATOR_KIND,
    SCROLLBAR_KIND,
    ROOT_SCROLL_ID,
    PROGRESS_KIND,
    SPACER_KIND,
    Button,
    ColumnView,
    CONTAINER_KIND,
    CounterView,
    Label,
    TEXT_INPUT_VIEW_KIND,
    ViewNode,
    make_row,
)
from .testing import TestRenderer, TestWindow, test_check
from .window import WindowBackend, WindowConfig
from .windowing import WindowId, WindowManager, WindowState
from .platform import PlatformSurface, PlatformTarget, SurfaceConfig
from .platform_adapters import (
    ContractBackend,
    PlatformAdapter,
    android_backend,
    headless_backend,
    ios_backend,
    web_backend,
)
from .host_contract import (
    HOST_NATIVE,
    HOST_PORTABLE_BRIDGE,
    HostContract,
    host_contract,
)
from .native_widgets import (
    NativeWidgetDescriptor,
    NativeWidgetRegistry,
    NATIVE_WIDGET_LABEL,
    NATIVE_WIDGET_BUTTON,
    NATIVE_WIDGET_TEXT_INPUT,
    NATIVE_WIDGET_CHECKBOX,
    NATIVE_WIDGET_SLIDER,
    NATIVE_WIDGET_SWITCH,
    NATIVE_WIDGET_RADIO,
    NATIVE_WIDGET_IMAGE,
    NATIVE_WIDGET_TEXT_AREA,
    NATIVE_WIDGET_COMBO_BOX,
    NATIVE_WIDGET_LIST,
    NATIVE_WIDGET_TABLE,
    NATIVE_WIDGET_TREE,
    NATIVE_WIDGET_MENU,
    NATIVE_WIDGET_DIALOG,
    NATIVE_WIDGET_TABS,
    NATIVE_WIDGET_SEPARATOR,
    NATIVE_WIDGET_CANVAS,
    NATIVE_WIDGET_CUSTOM,
    native_widget_kind,
)
from .targets import AndroidBackend, IOSBackend, WebBackend
from .scenarios import (
    SCENARIO_NONE,
    SCENARIO_FORM,
    SCENARIO_THEME,
    SCENARIO_COLLECTION,
    SCENARIO_TEXT,
    SCENARIO_PLOT,
    SCENARIO_CAPABILITY,
    SCENARIO_FRACTAL,
    ScenarioDescriptor,
    ScenarioRegistry,
    ThemeModeFixture,
    ScenarioStep,
    FractalBenchmarkFixture,
    TextCorpusFixture,
    CanvasSceneFixture,
    CANVAS_SCENE_PRIMITIVES,
    CANVAS_SCENE_THEME_DARK,
    CANVAS_SCENE_THEME_LIGHT,
    CANVAS_SCENE_PLOT,
    canonical_scenarios,
    canonical_canvas_scene_fixtures,
    canonical_canvas_scene_fixture,
    make_canvas_scene,
    canonical_form_title,
    canonical_form_hint,
    canonical_form_submit_label,
    canonical_theme_title,
    canonical_theme_selector_label,
    canonical_theme_modes,
    canonical_theme_mode_name,
    canonical_theme_status,
    canonical_theme_golden_mode,
    canonical_text_coretext_fixture,
    canonical_text_fallback_fixture,
    canonical_text_fallback_caption,
    canonical_text_combining_fixture,
    canonical_text_rtl_fixture,
    canonical_text_auto_rtl_fixture,
    canonical_text_mixed_bidi_fixture,
    canonical_text_corpus,
    canonical_capability_title,
    canonical_capability_initial_status,
    canonical_capability_hint,
    canonical_capability_steps,
    canonical_fractal_cases,
    canonical_fractal_preset_ids,
    canonical_fractal_depths,
    InteractionScenario,
    make_interaction_foundation_scenario,
)
from .performance import (
    FRAME_BUDGET_60_HZ_MS,
    FRAME_BUDGET_120_HZ_MS,
    PerformanceCounters,
    PerformanceReport,
)
from .execution import (
    DependencyEdge,
    ExecutionWorkCounters,
    KeyedSubtreeSchedule,
    KeyedChildExecutor,
    KeyedSubtreeExecutor,
    LocalizedExecution,
    TypedSubtreeExecutor,
)
from .plot_selection import PlotSelection, selection_from_keys
from .plot_render import (
    PLOT_RENDER_LINES,
    PLOT_RENDER_INSTANCES,
    PLOT_RENDER_LINE_STRIDE,
    PLOT_RENDER_INSTANCE_STRIDE,
    PlotRenderBatch,
    PlotRenderLine,
    PlotRenderInstance,
    PlotRenderPacket,
)
from .virtual_view import VirtualItemBuilder, VirtualizedList
from .svg import SvgSceneRenderer
from .coretext import MacOSTextShaper
from .harfbuzz import HarfBuzzTextShaper
from .metal import MacOSMetalCanvasPainter, MacOSMetalRenderer, MacOSMetalWindow
from .live_script import (
    LIVE_SCRIPT_CANVAS_ID,
    LIVE_SCRIPT_DETAIL_ID,
    LIVE_SCRIPT_STATUS_ID,
    LIVE_SCRIPT_TITLE_ID,
    LiveScriptState,
)


def moxi_version() -> String:
    """Return the package version embedded in this release."""
    return "0.6.0"
