"""Moxi's public package boundary."""

from .accessibility import (
    AccessibilitySnapshot,
    ROLE_BUTTON,
    ROLE_CHECKBOX,
    ROLE_CONTAINER,
    ROLE_LABEL,
    ROLE_NONE,
    ROLE_SPACER,
    ROLE_TEXT_INPUT,
    ROLE_PROGRESS_INDICATOR,
    ROLE_SLIDER,
    ROLE_SWITCH,
    ROLE_RADIO,
    ROLE_IMAGE,
    ROLE_TEXT_AREA,
    ROLE_COMBO_BOX,
    ROLE_LIST,
    ROLE_TABLE,
    ROLE_TREE,
    ROLE_MENU,
    ROLE_DIALOG,
    ROLE_TAB_GROUP,
    ROLE_CANVAS,
    ROLE_SEPARATOR,
    Semantics,
    ACTION_NONE,
    ACTION_PRESS,
    ACTION_INCREMENT,
    ACTION_DECREMENT,
    ACTION_SELECT,
    ACTION_EXPAND,
    ACTION_COLLAPSE,
)
from .geometry import Point, Rect, Size, Transform
from .backend import (
    BACKEND_GPU,
    BACKEND_HEADLESS,
    BACKEND_LINUX,
    BACKEND_MACOS_APPKIT,
    BACKEND_WINDOWS,
    BACKEND_IOS,
    BACKEND_ANDROID,
    BACKEND_WEB,
    BackendCapabilities,
    backend_capabilities,
)
from .event import (
    CLICK_KIND,
    COMPOSITION_END_KIND,
    COMPOSITION_UPDATE_KIND,
    FRAME_TICK_KIND,
    KEY_BACKSPACE,
    KEY_A,
    KEY_C,
    KEY_DELETE,
    KEY_DOWN,
    KEY_END,
    KEY_ENTER,
    KEY_ESCAPE,
    KEY_HOME,
    KEY_LEFT,
    KEY_RIGHT,
    KEY_SPACE,
    KEY_TAB,
    KEY_V,
    KEY_X,
    KEY_UP,
    POINTER_MOVE_KIND,
    POINTER_UP_KIND,
    SCROLL_KIND,
    DRAG_BEGIN_KIND,
    DRAG_UPDATE_KIND,
    DROP_KIND,
    TASK_RESULT_KIND,
    TOUCH_BEGIN_KIND,
    TOUCH_UPDATE_KIND,
    TOUCH_END_KIND,
    POINTER_CANCEL_KIND,
    ACTION_KIND,
    KEY_DOWN_KIND,
    MOD_COMMAND,
    MOD_CONTROL,
    MOD_OPTION,
    MOD_SHIFT,
    NONE_KIND,
    NO_ACTION,
    POINTER_DOWN_KIND,
    TEXT_INPUT_KIND,
    WINDOW_RESIZED_KIND,
    ClickEvent,
    CompositionEvent,
    Event,
    FrameEvent,
    KeyEvent,
    PointerEvent,
    TouchEvent,
    ResizeEvent,
    ScrollEvent,
    TaskEvent,
    DragEvent,
    ActionEvent,
    SemanticActionEvent,
    TextInputEvent,
)
from .component import Component, ComponentSlot
from .clipboard import ClipboardBackend, MemoryClipboard
from .capability import (
    CALLER_AGENT,
    CALLER_SYSTEM,
    CALLER_UI,
    CAPABILITY_BUSY,
    CAPABILITY_DISABLED,
    CAPABILITY_EXECUTOR_REQUIRED,
    CAPABILITY_HANDLER_MISMATCH,
    CAPABILITY_HANDLER_NOT_REGISTERED,
    CAPABILITY_INVALID,
    CAPABILITY_NOT_FOUND,
    CAPABILITY_OK,
    CAPABILITY_QUEUE_FULL,
    CAPABILITY_REQUIRES_APPROVAL,
    CAPABILITY_SCHEMA_INVALID,
    CAPABILITY_UNAVAILABLE,
    CapabilityBus,
    CapabilityApproval,
    CapabilityDescriptor,
    CapabilityHandler,
    CapabilityInvocation,
    CapabilityResult,
    SIDE_EFFECT_DESTRUCTIVE,
    SIDE_EFFECT_LOCAL,
    SIDE_EFFECT_NETWORK,
    SIDE_EFFECT_NONE,
)
from .conversation import ChatMessage, ConversationContext
from .controls import (
    ButtonControl,
    CheckboxControl,
    ImageControl,
    LabelControl,
    MultilineTextControl,
    ComboBoxControl,
    ListControl,
    TableControl,
    TreeControl,
    MenuControl,
    DialogControl,
    TabsControl,
    CanvasControl,
    SeparatorControl,
    ProgressControl,
    RadioControl,
    SliderControl,
    SwitchControl,
    TextInputControl,
    TextInputState,
    SliderState,
    ToggleState,
    RadioGroupState,
    MultilineTextState,
)
from .control_state import (
    CanvasState,
    ComboBoxState,
    DialogState,
    ListState,
    MenuState,
    SelectionState,
    TableState,
    TabsState,
    TreeState,
)
from .app import COUNTER_INCREMENT_ACTION, CounterState
from .alignment import AlignmentState
from .app_runtime import App
from .form import FormState
from .composed import (
    COMPOSED_COUNTER_ID_OFFSET,
    COMPOSED_COUNTER_SLOT_ID,
    COMPOSED_TITLE_ID,
    ComposedState,
)
from .nested import NestedState
from .row import NEXT_BUTTON_ID, PREVIOUS_BUTTON_ID, RowState
from .wxstyle import (
    WX_ACTIONS_ID,
    WX_AGENT_RESET_BUTTON_ID,
    WX_AGENT_RESET_ACTION,
    WX_APPROVE_RESET_ID,
    WX_APPROVE_RESET_ACTION,
    WX_APPROVAL_STATUS_ID,
    WX_ADVANCED_ID,
    WX_SLIDER_ID,
    WX_SWITCH_ID,
    WX_RADIO_ID,
    WX_IMAGE_ID,
    WX_MULTILINE_ID,
    WX_COMBO_ID,
    WX_LIST_ID,
    WX_TABLE_ID,
    WX_TREE_ID,
    WX_MENU_ID,
    WX_DIALOG_ID,
    WX_TABS_ID,
    WX_CANVAS_ID,
    WX_SEPARATOR_ID,
    WX_BACKEND_ID,
    WX_BODY_ID,
    WX_CANCEL_BUTTON_ID,
    WX_CAPABILITIES_ID,
    WX_CAPABILITY_STATUS_ID,
    WX_COMPONENT_SLOT_ID,
    WX_COUNTER_ID_OFFSET,
    WX_CONTEXT_ID,
    WX_HEADER_ID,
    WX_HELP_ID,
    WX_LAYOUT_ID,
    WX_NAME_FIELD_ID,
    WX_NAME_LABEL_ID,
    WX_OK_BUTTON_ID,
    WX_PANEL_ID,
    WX_PROGRESS_ID,
    WX_RICH_TEXT_ID,
    WX_REMEMBER_ID,
    WX_RESET_BUTTON_ID,
    WX_SPACER_ID,
    WX_STATUS_ID,
    WX_SUBTITLE_ID,
    WX_SUBMIT_ACTION,
    WX_CANCEL_ACTION,
    WX_REMEMBER_ACTION,
    WX_RESET_ACTION,
    WX_TITLE_ID,
    WxStyleState,
)
from .wrapped import WRAPPED_BODY_ID, WRAPPED_TITLE_ID, WrappedTextState
from .layout import (
    ALIGN_CENTER,
    ALIGN_END,
    ALIGN_START,
    ALIGN_STRETCH,
    COLUMN_AXIS,
    JUSTIFY_CENTER,
    JUSTIFY_END,
    JUSTIFY_SPACE_BETWEEN,
    JUSTIFY_START,
    ROW_AXIS,
    ColumnLayout,
    RowLayout,
    LAYOUT_GRID,
    LAYOUT_LINEAR,
    LAYOUT_PORTAL,
    LAYOUT_SPLIT,
    LAYOUT_STACK,
)
from .layout_primitives import (
    GridCell,
    ScrollState,
    VirtualRange,
    VirtualListState,
    VirtualRecycleItem,
    VirtualRecycler,
    clamp_fraction,
    grid_cell,
    split_extent,
    variable_visible_range,
    visible_range,
)
from .measure import TextMeasurement, measure_text, measure_text_wrapped
from .text_layout import (
    TEXT_DIRECTION_LTR,
    TEXT_DIRECTION_RTL,
    TEXT_DIRECTION_AUTO,
    TEXT_LAYOUT_ESTIMATE,
    TEXT_LAYOUT_NATIVE,
    TEXT_LAYOUT_PORTABLE,
    RichText,
    TextLayoutRequest,
    TextLayoutResult,
    TextSpan,
    layout_rich_text,
    layout_text,
)
from .text_shaping import (
    SHAPER_NATIVE,
    SHAPER_PORTABLE_ESTIMATE,
    SCRIPT_ARABIC_HEBREW,
    SCRIPT_CJK,
    SCRIPT_COMMON,
    SCRIPT_CYRILLIC,
    SCRIPT_DEVANAGARI,
    SCRIPT_EMOJI,
    SCRIPT_LATIN,
    PortableTextShaper,
    ShapedGlyph,
    ShapedRun,
    ShapedText,
    TextShaper,
    fallback_font_id,
    script_id,
    shape_text,
)
from .text_boundary import (
    clamp_text_boundary,
    codepoint_at,
    is_combining_mark,
    is_emoji_modifier,
    is_extend,
    is_regional_indicator,
    is_variation_selector,
    next_text_boundary,
    previous_text_boundary,
)
from .reactivity import (
    ActionMessage,
    ActionQueue,
    MemoKey,
    StateScope,
    StateVersion,
    StringLens,
    StringMemo,
)
from .tasks import (
    TASK_CANCELLED,
    TASK_COMPLETED,
    TASK_FAILED,
    TASK_PENDING,
    TaskHandle,
    TaskRecord,
    TaskResult,
    TaskScheduler,
)
from .resources import (
    RESOURCE_DATA,
    RESOURCE_FONT,
    RESOURCE_IMAGE,
    RESOURCE_NONE,
    ImageResource,
    FontResource,
    ResourceHandle,
    ResourceResolver,
    ResourceStore,
)
from .scene import (
    SCENE_CLIP,
    SCENE_IMAGE,
    SCENE_LINE,
    SCENE_POP_CLIP,
    SCENE_POP_LAYER,
    SCENE_PUSH_LAYER,
    SCENE_RECT,
    SCENE_ROUNDED_RECT,
    SCENE_TEXT,
    SCENE_PATH,
    SCENE_LINEAR_GRADIENT,
    SCENE_TRANSFORM,
    SCENE_RESET_TRANSFORM,
    Scene,
    SceneCommand,
    SceneRenderer,
    SceneRecorder,
)
from .software import SoftwareSceneRenderer
from .invalidation import (
    INVALIDATE_ACCESSIBILITY,
    INVALIDATE_ALL,
    INVALIDATE_CONTENT,
    INVALIDATE_LAYOUT,
    INVALIDATE_NONE,
    INVALIDATE_STRUCTURE,
    Invalidation,
)
from .animation import (
    EASE_IN,
    EASE_IN_OUT,
    EASE_LINEAR,
    EASE_OUT,
    Animation,
    eased_progress,
)
from .paint import PANEL_KIND, SURFACE_KIND, PaintCommand, PaintCommands, Renderer, scene_from_paint
from .runtime import ColumnRuntime, CounterRuntime, Runtime, Widget
from .style import (
    Color,
    Panel,
    Style,
    Theme,
    default_button_style,
    default_checkbox_style,
    default_label_style,
    default_panel_style,
    default_progress_style,
    default_surface_style,
    default_text_input_style,
    default_image_style,
    default_multiline_style,
    default_radio_style,
    default_slider_style,
    default_switch_style,
)
from .view import (
    BUTTON_KIND,
    CHECKBOX_KIND,
    LABEL_KIND,
    SLIDER_KIND,
    SWITCH_KIND,
    RADIO_KIND,
    IMAGE_KIND,
    MULTILINE_TEXT_KIND,
    COMBO_BOX_KIND,
    LIST_KIND,
    TABLE_KIND,
    TREE_KIND,
    MENU_KIND,
    DIALOG_KIND,
    TABS_KIND,
    CANVAS_KIND,
    SEPARATOR_KIND,
    PROGRESS_KIND,
    SPACER_KIND,
    Button,
    ColumnView,
    CONTAINER_KIND,
    CounterView,
    Label,
    TEXT_INPUT_VIEW_KIND,
    ViewNode,
    make_row,
)
from .testing import TestRenderer, TestWindow, test_check
from .window import WindowBackend, WindowConfig
from .windowing import WindowId, WindowManager, WindowState
from .platform import PlatformSurface, PlatformTarget, SurfaceConfig
from .platform_adapters import (
    ContractBackend,
    PlatformAdapter,
    android_backend,
    headless_backend,
    ios_backend,
    web_backend,
)
from .host_contract import (
    HOST_NATIVE,
    HOST_PORTABLE_BRIDGE,
    HostContract,
    host_contract,
)
from .native_widgets import (
    NativeWidgetDescriptor,
    NativeWidgetRegistry,
    NATIVE_WIDGET_BUTTON,
    NATIVE_WIDGET_TEXT_INPUT,
    native_widget_kind,
)
from .targets import AndroidBackend, IOSBackend, WebBackend
from .scenarios import make_plot_data_fixture, make_plot_scenario
from .performance import (
    FRAME_BUDGET_60_HZ_MS,
    FRAME_BUDGET_120_HZ_MS,
    PerformanceCounters,
    PerformanceReport,
)
from .execution import DependencyEdge, LocalizedExecution
from .plotting import (
    PLOT_AREA,
    PLOT_BAR,
    PLOT_BAND,
    PLOT_BUBBLE,
    PLOT_COLUMN,
    PLOT_DOT,
    PLOT_ERROR_BAR,
    PLOT_LINE,
    PLOT_RECT,
    PLOT_RULE,
    PLOT_SCATTER,
    PLOT_STEP,
    PLOT_TICK,
    PLOT_TEXT,
    PLOT_INTERVAL,
    PLOT_HISTOGRAM,
    PLOT_DENSITY,
    PLOT_ECDF,
    PLOT_BOX,
    PLOT_HEATMAP,
    PLOT_HEXBIN,
    PLOT_REGRESSION,
    SCALE_BAND,
    SCALE_CATEGORICAL,
    SCALE_DIVERGING,
    SCALE_LINEAR,
    SCALE_LOG,
    SCALE_ORDINAL,
    SCALE_POINT,
    SCALE_POWER,
    SCALE_SQRT,
    SCALE_QUANTILE,
    SCALE_QUANTIZE,
    SCALE_SEQUENTIAL,
    SCALE_SYMLOG,
    SCALE_TEMPORAL,
    SCALE_THRESHOLD,
    Plot,
    PlotHit,
    PlotPoint,
    PlotScale,
    PlotSeries,
)
from .plot_data import (
    COLUMN_BOOL,
    COLUMN_DURATION,
    COLUMN_CATEGORY,
    COLUMN_FLOAT64,
    COLUMN_FLOAT32,
    COLUMN_INT64,
    COLUMN_STRING,
    COLUMN_TIMESTAMP,
    PlotColumn,
    PlotDataSnapshot,
    PlotDataTable,
    PlotDataView,
    column_kind_name,
)
from .plot_spec import (
    CHANNEL_ANGLE,
    CHANNEL_COLOR,
    CHANNEL_COLUMN,
    CHANNEL_DETAIL,
    CHANNEL_FACET,
    CHANNEL_FILL,
    CHANNEL_HREF,
    CHANNEL_KEY,
    CHANNEL_OPACITY,
    CHANNEL_ORDER,
    CHANNEL_RADIUS,
    CHANNEL_ROW,
    CHANNEL_SHAPE,
    CHANNEL_SIZE,
    CHANNEL_STROKE,
    CHANNEL_TEXT,
    CHANNEL_TOOLTIP,
    CHANNEL_X,
    CHANNEL_X2,
    CHANNEL_Y,
    CHANNEL_Y2,
    COMPOSITION_FACET,
    COMPOSITION_HORIZONTAL,
    COMPOSITION_LAYER,
    COMPOSITION_VERTICAL,
    INTERACTION_BRUSH,
    INTERACTION_CLICK_SELECT,
    INTERACTION_HOVER,
    INTERACTION_KEYBOARD,
    INTERACTION_LASSO,
    INTERACTION_PAN_ZOOM,
    PLOT_SPEC_VERSION,
    TRANSFORM_FILTER_BETWEEN,
    TRANSFORM_FILTER_GREATER,
    TRANSFORM_BIN,
    TRANSFORM_CALCULATE,
    TRANSFORM_AGGREGATE,
    TRANSFORM_GROUP,
    TRANSFORM_IMPUTE,
    TRANSFORM_LIMIT,
    TRANSFORM_ROLLING_MEAN,
    TRANSFORM_SAMPLE,
    TRANSFORM_SORT,
    TRANSFORM_STACK,
    TRANSFORM_HISTOGRAM,
    TRANSFORM_DENSITY,
    TRANSFORM_ECDF,
    TRANSFORM_BOX,
    TRANSFORM_HEATMAP,
    TRANSFORM_HEXBIN,
    TRANSFORM_REGRESSION,
    TYPE_BOOL,
    TYPE_NOMINAL,
    TYPE_ORDINAL,
    TYPE_QUANTITATIVE,
    TYPE_TEMPORAL,
    PlotAnnotation,
    PlotEncoding,
    PlotLayer,
    PlotInteraction,
    PlotScaleSpec,
    PlotSpec,
    PlotTransform,
    channel_name,
    composition_name,
    data_type_name,
    interaction_name,
    plot_from_spec,
    plot_mark_name,
    plot_spec_from_json,
    scale_kind_name,
    transform_name,
)
from .plot_runtime import PlotRuntime
from .plot_view import PlotControl, PlotView
from .plot_selection import PlotSelection, selection_from_keys
from .plot_link import PlotLink
from .virtual_view import VirtualItemBuilder, VirtualizedList
from .svg import SvgSceneRenderer
from .coretext import MacOSTextShaper
from .harfbuzz import HarfBuzzTextShaper
from .metal import MacOSMetalRenderer, MacOSMetalWindow


def moxi_version() -> String:
    """Return the package version embedded in this release."""
    return "0.5.0"
